import { Appointment } from '../types/appointment';

export const sampleAppointments: Appointment[] = [
  {
    id: 1,
    doctor: 'Dr. García',
    fecha: '2024-01-15',
    hora: '10:00 AM',
    estado: 'confirmed',
    tipo: 'Consultation',
    especialidad: 'General Medicine',
    descripcion: 'Follow-up consultation for persistent headache.',
    cancelada: false,
    motivoRechazo: '',
    descripcionCita: '',
    examenes: []
  },
  {
    id: 2,
    doctor: 'Dr. Martínez',
    fecha: '2024-01-15',
    hora: '11:30 AM',
    estado: 'pending',
    tipo: 'Follow-up',
    especialidad: 'Cardiology',
    descripcion: 'Regular check-up for heart condition.',
    cancelada: false,
    motivoRechazo: '',
    descripcionCita: '',
    examenes: []
  },
  {
    id: 3,
    doctor: 'Dr. González',
    fecha: '2024-01-16',
    hora: '09:00 AM',
    estado: 'completed',
    tipo: 'Emergency',
    especialidad: 'Emergency Medicine',
    descripcion: 'Chest pain requiring immediate attention.',
    cancelada: false,
    motivoRechazo: '',
    descripcionCita: 'Patient evaluated, ECG normal. Prescribed medication for gastritis.',
    examenes: ['ECG', 'Blood Pressure']
  },
  {
    id: 4,
    doctor: 'Dr. Ortega',
    fecha: '2024-01-16',
    hora: '14:00 PM',
    estado: 'cancelled',
    tipo: 'Consultation',
    especialidad: 'Dermatology',
    descripcion: 'Skin rash evaluation.',
    cancelada: true,
    motivoRechazo: 'Patient requested cancellation due to scheduling conflict.',
    descripcionCita: '',
    examenes: []
  },
  {
    id: 5,
    doctor: 'Dr. Pérez',
    fecha: '2024-01-17',
    hora: '10:30 AM',
    estado: 'confirmed',
    tipo: 'Check-up',
    especialidad: 'Dentistry',
    descripcion: 'Routine dental cleaning and examination.',
    cancelada: false,
    motivoRechazo: '',
    descripcionCita: '',
    examenes: []
  },
  {
    id: 6,
    doctor: 'Dr. Núñez',
    fecha: '2024-01-17',
    hora: '15:00 PM',
    estado: 'pending',
    tipo: 'Consultation',
    especialidad: 'Ophthalmology',
    descripcion: 'Vision problems and eye strain.',
    cancelada: false,
    motivoRechazo: '',
    descripcionCita: '',
    examenes: []
  },
  {
    id: 7,
    doctor: 'Dr. Santos',
    fecha: '2024-01-18',
    hora: '11:00 AM',
    estado: 'completed',
    tipo: 'Follow-up',
    especialidad: 'Cardiology',
    descripcion: 'Follow-up for hypertension management.',
    cancelada: false,
    motivoRechazo: '',
    descripcionCita: 'Blood pressure under control. Continue current medication.',
    examenes: ['Blood Pressure', 'Blood Test']
  },
  {
    id: 8,
    doctor: 'Dr. Ríos',
    fecha: '2024-01-18',
    hora: '16:00 PM',
    estado: 'confirmed',
    tipo: 'Consultation',
    especialidad: 'Gynecology',
    descripcion: 'Annual gynecological examination.',
    cancelada: false,
    motivoRechazo: '',
    descripcionCita: '',
    examenes: []
  },
  {
    id: 9,
    doctor: 'Dr. López',
    fecha: '2024-01-19',
    hora: '09:30 AM',
    estado: 'pending',
    tipo: 'Consultation',
    especialidad: 'Neurology',
    descripcion: 'Persistent migraines evaluation.',
    cancelada: false,
    motivoRechazo: '',
    descripcionCita: '',
    examenes: []
  },
  {
    id: 10,
    doctor: 'Dr. Vega',
    fecha: '2024-01-19',
    hora: '13:00 PM',
    estado: 'completed',
    tipo: 'Check-up',
    especialidad: 'General Medicine',
    descripcion: 'Annual physical examination.',
    cancelada: false,
    motivoRechazo: '',
    descripcionCita: 'Patient in good health. All vital signs normal.',
    examenes: ['Blood Test', 'Urinalysis', 'X-Ray']
  }
];
